import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ContextProvider} from "@/context/context";
import Header from "@/components/Header";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet"/>
      <link href="https://fonts.cdnfonts.com/css/bitterslide-evelwhite" rel="stylesheet"/>
      <link href="https://fonts.cdnfonts.com/css/grandiflora-one" rel="stylesheet"/>
      <link href="https://fonts.cdnfonts.com/css/vintage-glory" rel="stylesheet"/>
      <link href="https://fonts.cdnfonts.com/css/cairo-play" rel="stylesheet"/>
      <link href="https://fonts.cdnfonts.com/css/afacad" rel="stylesheet"/>
                

                
                
      </head>
      <ContextProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
          <Toaster 
          position="top-right"
          toastOptions={{
            style: {
              border: "1px solid #333",
              padding: "16px",
              color: "#333",
              fontSize: "16px",
            },
            duration: 5000,
            
          }}/>
        </body>
      </ContextProvider>
    </html>
  );
}
